/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import com.itextpdf.text.io.StreamUtil;
import java.util.Stack;

/**
 *
 * @author ADMIN
 */
public class Calculator extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    private StringBuilder input = new StringBuilder();
    int xx, xy;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calculatorInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        divideBt = new javax.swing.JButton();
        oneBt = new javax.swing.JButton();
        twoBt = new javax.swing.JButton();
        threeBt = new javax.swing.JButton();
        additionBt = new javax.swing.JButton();
        fourBt = new javax.swing.JButton();
        sevenBt = new javax.swing.JButton();
        zeroBt = new javax.swing.JButton();
        fiveBt = new javax.swing.JButton();
        sixBt = new javax.swing.JButton();
        minusBt = new javax.swing.JButton();
        eightBt = new javax.swing.JButton();
        nineBt = new javax.swing.JButton();
        multiplicationBt = new javax.swing.JButton();
        clearBt = new javax.swing.JButton();
        equalBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 58, 138));

        calculatorInput.setEditable(false);
        calculatorInput.setBackground(new java.awt.Color(204, 204, 204));
        calculatorInput.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        calculatorInput.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(243, 244, 246));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 65, 81), 1, true));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        divideBt.setBackground(new java.awt.Color(251, 191, 36));
        divideBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        divideBt.setForeground(new java.awt.Color(0, 0, 0));
        divideBt.setText("/");
        divideBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtActionPerformed(evt);
            }
        });
        jPanel2.add(divideBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 80, 60));

        oneBt.setBackground(new java.awt.Color(251, 191, 36));
        oneBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        oneBt.setForeground(new java.awt.Color(0, 0, 0));
        oneBt.setText("1");
        oneBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtActionPerformed(evt);
            }
        });
        jPanel2.add(oneBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        twoBt.setBackground(new java.awt.Color(251, 191, 36));
        twoBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        twoBt.setForeground(new java.awt.Color(0, 0, 0));
        twoBt.setText("2");
        twoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtActionPerformed(evt);
            }
        });
        jPanel2.add(twoBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 60));

        threeBt.setBackground(new java.awt.Color(251, 191, 36));
        threeBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        threeBt.setForeground(new java.awt.Color(0, 0, 0));
        threeBt.setText("3");
        threeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtActionPerformed(evt);
            }
        });
        jPanel2.add(threeBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 60));

        additionBt.setBackground(new java.awt.Color(251, 191, 36));
        additionBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        additionBt.setForeground(new java.awt.Color(0, 0, 0));
        additionBt.setText("+");
        additionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionBtActionPerformed(evt);
            }
        });
        jPanel2.add(additionBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 60));

        fourBt.setBackground(new java.awt.Color(251, 191, 36));
        fourBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        fourBt.setForeground(new java.awt.Color(0, 0, 0));
        fourBt.setText("4");
        fourBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtActionPerformed(evt);
            }
        });
        jPanel2.add(fourBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 60));

        sevenBt.setBackground(new java.awt.Color(251, 191, 36));
        sevenBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        sevenBt.setForeground(new java.awt.Color(0, 0, 0));
        sevenBt.setText("7");
        sevenBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtActionPerformed(evt);
            }
        });
        jPanel2.add(sevenBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 60));

        zeroBt.setBackground(new java.awt.Color(251, 191, 36));
        zeroBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        zeroBt.setForeground(new java.awt.Color(0, 0, 0));
        zeroBt.setText("0");
        zeroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtActionPerformed(evt);
            }
        });
        jPanel2.add(zeroBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 60));

        fiveBt.setBackground(new java.awt.Color(251, 191, 36));
        fiveBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        fiveBt.setForeground(new java.awt.Color(0, 0, 0));
        fiveBt.setText("5");
        fiveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtActionPerformed(evt);
            }
        });
        jPanel2.add(fiveBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 60));

        sixBt.setBackground(new java.awt.Color(251, 191, 36));
        sixBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        sixBt.setForeground(new java.awt.Color(0, 0, 0));
        sixBt.setText("6");
        sixBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtActionPerformed(evt);
            }
        });
        jPanel2.add(sixBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 60));

        minusBt.setBackground(new java.awt.Color(251, 191, 36));
        minusBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        minusBt.setForeground(new java.awt.Color(0, 0, 0));
        minusBt.setText("-");
        minusBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtActionPerformed(evt);
            }
        });
        jPanel2.add(minusBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 80, 60));

        eightBt.setBackground(new java.awt.Color(251, 191, 36));
        eightBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        eightBt.setForeground(new java.awt.Color(0, 0, 0));
        eightBt.setText("8");
        eightBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtActionPerformed(evt);
            }
        });
        jPanel2.add(eightBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 60));

        nineBt.setBackground(new java.awt.Color(251, 191, 36));
        nineBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        nineBt.setForeground(new java.awt.Color(0, 0, 0));
        nineBt.setText("9");
        nineBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtActionPerformed(evt);
            }
        });
        jPanel2.add(nineBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 60));

        multiplicationBt.setBackground(new java.awt.Color(251, 191, 36));
        multiplicationBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        multiplicationBt.setForeground(new java.awt.Color(0, 0, 0));
        multiplicationBt.setText("X");
        multiplicationBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationBtActionPerformed(evt);
            }
        });
        jPanel2.add(multiplicationBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 80, 60));

        clearBt.setBackground(new java.awt.Color(251, 191, 36));
        clearBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        clearBt.setForeground(new java.awt.Color(0, 0, 0));
        clearBt.setText("C");
        clearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtActionPerformed(evt);
            }
        });
        jPanel2.add(clearBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, 60));

        equalBt.setBackground(new java.awt.Color(251, 191, 36));
        equalBt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        equalBt.setForeground(new java.awt.Color(0, 0, 0));
        equalBt.setText("=");
        equalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtActionPerformed(evt);
            }
        });
        jPanel2.add(equalBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculatorInput)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(calculatorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtActionPerformed
        appendInput("1");
    }//GEN-LAST:event_oneBtActionPerformed

    private void twoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtActionPerformed
        appendInput("2");
    }//GEN-LAST:event_twoBtActionPerformed

    private void threeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtActionPerformed
        appendInput("3");
    }//GEN-LAST:event_threeBtActionPerformed

    private void fourBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtActionPerformed
        appendInput("4");
    }//GEN-LAST:event_fourBtActionPerformed

    private void fiveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtActionPerformed
        appendInput("5");
    }//GEN-LAST:event_fiveBtActionPerformed

    private void sixBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtActionPerformed
        appendInput("6");
    }//GEN-LAST:event_sixBtActionPerformed

    private void sevenBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtActionPerformed
        appendInput("7");
    }//GEN-LAST:event_sevenBtActionPerformed

    private void eightBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtActionPerformed
        appendInput("8");
    }//GEN-LAST:event_eightBtActionPerformed

    private void nineBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtActionPerformed
        appendInput("9");
    }//GEN-LAST:event_nineBtActionPerformed

    private void zeroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtActionPerformed
        appendInput("0");
    }//GEN-LAST:event_zeroBtActionPerformed

    private void additionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionBtActionPerformed
        appendInput("+");
    }//GEN-LAST:event_additionBtActionPerformed

    private void minusBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBtActionPerformed
        appendInput("-");
    }//GEN-LAST:event_minusBtActionPerformed

    private void multiplicationBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationBtActionPerformed
        appendInput("*");
    }//GEN-LAST:event_multiplicationBtActionPerformed

    private void divideBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtActionPerformed
        appendInput("/");
    }//GEN-LAST:event_divideBtActionPerformed

    private void equalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtActionPerformed
        calculateResult();
    }//GEN-LAST:event_equalBtActionPerformed

    private void clearBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtActionPerformed
        calculatorInput.setText("");
    }//GEN-LAST:event_clearBtActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void appendInput(String value) {
        input.append(value);
        calculatorInput.setText(input.toString());
    }

    private double evaluateExpression(String expr) {
        Stack<Double> numbers = new Stack<>();
        Stack<Character> operators = new Stack<>();

        for (int i = 0; i < expr.length(); i++) {
            char c = expr.charAt(i);

            if (Character.isDigit(c) || c == '.') {
                StringBuilder num = new StringBuilder();
                while (i < expr.length() && (Character.isDigit(expr.charAt(i)) || expr.charAt(i) == '.')) {
                    num.append(expr.charAt(i++));
                }
                i--;
                numbers.push(Double.parseDouble(num.toString()));
            } else if (c == '+' || c == '-' || c == '*' || c == '/') {
                while (!operators.isEmpty() && hasPrecedence(c, operators.peek())) {
                    numbers.push(applyOp(operators.pop(), numbers.pop(), numbers.pop()));
                }
                operators.push(c);
            }
        }

        while (!operators.isEmpty()) {
            numbers.push(applyOp(operators.pop(), numbers.pop(), numbers.pop()));
        }

        return numbers.pop();
    }

    private boolean hasPrecedence(char op1, char op2) {
        if ((op1 == '*' || op1 == '/') && (op2 == '+' || op2 == '-')) {
            return false;
        }
        return true;
    }

    private double applyOp(char op, double b, double a) {
        switch (op) {
            case '+':
                return a + b;
            case '-':
                return a - b;
            case '*':
                return a * b;
            case '/':
                return b == 0 ? 0 : a / b;
        }
        return 0;
    }

    // When "=" button is pressed
    private void calculateResult() {
        try {
            double result = evaluateExpression(input.toString());
            calculatorInput.setText(String.valueOf(result));
            input.setLength(0);
        } catch (Exception e) {
            calculatorInput.setText("Error");
            input.setLength(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionBt;
    private javax.swing.JTextField calculatorInput;
    private javax.swing.JButton clearBt;
    private javax.swing.JButton divideBt;
    private javax.swing.JButton eightBt;
    private javax.swing.JButton equalBt;
    private javax.swing.JButton fiveBt;
    private javax.swing.JButton fourBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minusBt;
    private javax.swing.JButton multiplicationBt;
    private javax.swing.JButton nineBt;
    private javax.swing.JButton oneBt;
    private javax.swing.JButton sevenBt;
    private javax.swing.JButton sixBt;
    private javax.swing.JButton threeBt;
    private javax.swing.JButton twoBt;
    private javax.swing.JButton zeroBt;
    // End of variables declaration//GEN-END:variables
}
